excludes:
    scopes:
        - pattern: "devDependencies"
          reason: "DEV_DEPENDENCY_OF"
          comment: "Packages for development only."
    paths:
        - pattern: "npm/glide/**"
          reason: "BUILD_TOOL_OF"
          comment: "Template file for CD"
resolutions:
    issues:
        - message: ".*Collection contains no element matching the predicate.*"
          reason: "BUILD_TOOL_ISSUE"
          comment: "Error caused by a known problem in the build tool."
