name: Run the OSS review tool

inputs:
    folder_path:
        description: "The root folder to run the ORT tool from"
        required: true
        type: string

runs:
    using: "composite"
    steps:
        - name: Make folders
          shell: bash
          run: |
            echo "Running ORT tools for ${{ inputs.folder_path }}"
            FOLDER=${{ inputs.folder_path }}
            mkdir $FOLDER/ort_results
            
        - name: Run ORT tools
          shell: bash
          run: |
            /cli/build/install/ort/bin/ort --info analyze -f JSON -i $FOLDER -o $FOLDER/ort_results
            /cli/build/install/ort/bin/ort --info report -i $FOLDER/ort_results/analyzer-result.json -o $FOLDER/ort_results/ -f PlainTextTemplate

