name: Run the OSS review tool

inputs:
    folder_path:
        description: "The root folder to run the ORT tool from"
        required: true
        type: string

runs:
    using: "composite"
    steps:
        - name: Make folders
          shell: bash
          run: |
            echo "Running ORT tools for ${{ inputs.folder_path }}"
            FOLDER=${{ inputs.folder_path }}
            mkdir $FOLDER/ort_results
            
        - name: Run ORT tools
          uses: oss-review-toolkit/ort-ci-github-action@v1
          with:
            ort-cli-analyze-args: >
              -l -i $FOLDER 
              -l -o $FOLDER/ort_results 
              -l -f JSON
            ort-cli-report-args: >
              -l -i $FOLDER/ort_results/analyzer-result.json
              -l -o $FOLDER/ort_results/ 
              -l -f PlainTextTemplate
            run: >
               analyzer,
               reporter

