excludes:
  scopes:
    - pattern: "build-dependencies"
      reason: "BUILD_DEPENDENCY_OF"
      comment: "Packages for building the code only."
    - pattern: "dev-dependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only."
  paths:
    - pattern: ".*"
      reason: "BUILD_TOOL_OF"
      comment: "invisible"
resolutions:
  issues:
    - message: ".*Collection contains no element matching the predicate.*"
      reason: "BUILD_TOOL_ISSUE"
      comment: "Error caused by a known problem in the build tool."
